### ISSUE TITLE
[MMC4 Data Processing] questions on code and missing file `sizes.json` and `__len__`

### ISSUE THREAD

**Issue by Luodian** [mlfoundations/open_flamingo#206]
hi I do notice that in `data.py` the `get_dataset_size` function's behavior on handling mmc4 shards is somehow weird.

the `shards_list` seems conflict in these two lines.

```python
def get_dataset_size(shards):
    shards_list = list(braceexpand.braceexpand(shards))
    shards_list = shards
    dir_path = os.path.dirname(shards[0])
    sizes_filename = os.path.join(dir_path, "sizes.json")
    len_filename = os.path.join(dir_path, "__len__")
    if os.path.exists(sizes_filename):
        sizes = json.load(open(sizes_filename, "r"))
        total_size = sum(
            [int(sizes[os.path.basename(shard)]) if os.path.basename(shard) in sizes else 0 for shard in shards_list]
        )
    elif os.path.exists(len_filename):
        # FIXME this used to be eval(open(...)) but that seemed rather unsafe
        total_size = ast.literal_eval(open(len_filename, "r").read())
    else:
        total_size = None  # num samples undefined
        # some common dataset sizes (at time of authors last download)
        # CC3M (train): 2905954
        # CC12M: 10968539
        # LAION-400M: 407332084
        # LAION-2B (english): 2170337258
    num_shards = len(shards_list)
    return total_size, num_shards
```

And may I know where should the `sizes.json` come from? I converted some example shards using `convert_mmc4_to_wds.py` but didnt see a `sizes.json` and `__len__` file inside my folder. Here's my folder structure.
![image](https://github.com/mlfoundations/open_flamingo/assets/15847405/7ef954f5-8f12-4a65-bc45-a2217b391483)

**Comment by anas-awadalla** [comment]
Ah weird thanks for catching this typo. I will push a fix.

You shouldn’t need to a size.json or any other file to specify the size of the dataset. This is the case for some of the datasets we used internally but isn’t relevant for mmc4.

**Comment by anas-awadalla** [comment]
Resolved in #202

**Comment by ElegantLin** [comment]
Thanks for your great job! I still have a question about the `sizes.json` and `__len__` in https://github.com/mlfoundations/open_flamingo/blob/main/open_flamingo/train/data_utils.py#L61 because it is still in the main branch. Could you please give me an example of these two files?

Thanks!

**Comment by anas-awadalla** [comment]
@ElegantLin You don't need them! They are just for debugging purposes on our end.

**Comment by ElegantLin** [comment]
Got it. Thanks! I think the function `get_data_size` is just a helper function for you to debug which is not really used.
